measures_config:
    SpecFamily:
        standard: SPEC_STANDARD
        units:
            SPEC_STANDARD:
                convert: [{'mul': 1}]
                symbol: 'spec'
                name: 'standard for the specs'
                unece_code: 'fooCode'

            KILO_STANDARD:
                convert: [{'mul': 1000}]
                symbol: 'kilospec'
                name: 'kilo measure of the standard'
                unece_code: 'barCode'
                alternative_units: ['kylo']
