parameters:
    pim_extended_measures.resolver.class: Pim\Bundle\ExtendedMeasureBundle\Resolver\MeasureResolver

services:
    pim_extended_measures.resolver:
        class: '%pim_extended_measures.resolver.class%'
        arguments:
            - '%akeneo_measure.measures_config%'
