measures_config:
    Resolution:
        standard: DPI
        units:
            DPI:
                unece_code: 'E39'
                symbol: 'dpi'
                convert: [{'mul': 1}]
                name: 'dots per inch'
            PPI:
                unece_code: 'PQ'
                symbol: 'ppi'
                convert: [{'mul': 1}]
                name: 'pixel per inch'
